/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An ORGiD project configuration
 */
export type ORGiDCLIProject = OrgIdCliProjectReference;

export interface OrgIdCliProjectReference {
  /**
   * Project file note
   */
  note?: string;
  /**
   * Files deployments information
   */
  deployments?: ProjectDeploymentReference[];
  /**
   * Verifiable credentials
   */
  vcs?: ProjectVcReference[];
  /**
   * List of registered ORGiDs
   */
  orgIds?: ProjectOrgIdsReference[];
  /**
   * List of registered keys
   */
  keys?: ProjectKeysReference[];
  [k: string]: unknown;
}
export interface ProjectDeploymentReference {
  /**
   * A type of deployment
   */
  type: "ipfs" | "ipns" | "rest";
  /**
   * Path to the local file
   */
  path: string;
  /**
   * URI of deployed file
   */
  uri: string;
  /**
   * Deployment date in the ISO format
   */
  date: string;
  [k: string]: unknown;
}
export interface ProjectVcReference {
  /**
   * A type of VC
   */
  type: "VerifiableCredential" | "OrgJson";
  /**
   * ORGiD DID of the ORG.JSON
   */
  did?: string;
  /**
   * A verification method used a VC signature creation
   */
  method: string;
  /**
   * Path to the original credential subject source
   */
  payload: string;
  /**
   * Path to the created VC file
   */
  path: string;
  /**
   * URI of a deployed credential file
   */
  uri?: string;
  /**
   * VC creation date in the ISO format
   */
  date: string;
  [k: string]: unknown;
}
export interface ProjectOrgIdsReference {
  /**
   * ORGiD DID
   */
  did: string;
  /**
   * ORGiD DID salt
   */
  salt: string;
  /**
   * ORGiD owner
   */
  owner: string;
  /**
   * Path to saved ORG.JSON raw template
   */
  template?: string;
  /**
   * Creation/update date in the ISO format
   */
  date?: string;
  [k: string]: unknown;
}
/**
 * Registered key pair
 */
export interface ProjectKeysReference {
  /**
   * Type of key pair
   */
  type: "eip155";
  /**
   * A unique key pair tag
   */
  tag: string;
  /**
   * Public key
   */
  publicKey:
    | string
    | {
        [k: string]: unknown;
      };
  /**
   * Encrypted private key
   */
  privateKey: string;
  /**
   * Creation/update date in the ISO format
   */
  date?: string;
  [k: string]: unknown;
}
