/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An ORGiD project configuration
 */
export type ORGiDCLIProject = OrgIdCliProjectReference;

export interface OrgIdCliProjectReference {
  /**
   * Project file note
   */
  note?: string;
  /**
   * Files deployments information
   */
  deployments?: DeploymentReference[];
  /**
   * Verifiable credentials
   */
  vcs?: VcReference[];
  [k: string]: unknown;
}
export interface DeploymentReference {
  /**
   * A type of deployment
   */
  type: "ipfs" | "ipns" | "rest";
  /**
   * Path to the local file
   */
  path: string;
  /**
   * URI of deployed file
   */
  uri: string;
  /**
   * Deployment date in the ISO format
   */
  date: string;
  [k: string]: unknown;
}
export interface VcReference {
  /**
   * A type of VC
   */
  type: "VerifiableCredential" | "OrgJson";
  /**
   * ORGiD DID of the ORG.JSON
   */
  did?: string;
  /**
   * A verification method used a VC signature creation
   */
  method: string;
  /**
   * Path to the original credential subject source
   */
  payload: string;
  /**
   * Path to the created VC file
   */
  path: string;
  /**
   * URI of a deployed credential file
   */
  uri?: string;
  /**
   * VC creation date in the ISO format
   */
  date: string;
  [k: string]: unknown;
}
